
SELECT register('aboba','qwerty');
SELECT register('sanya','abcdef');
SELECT register('kostya','vskdvb');

INSERT INTO M_CHAT (NAME)
VALUES('chatic');

INSERT INTO M_USER_IN_CHAT (USER_ID, CHAT_ID, ROLE)
VALUES(1,1, 'CREATOR'), (2,1, 'REGULAR'), (3,1, 'REGULAR');

INSERT INTO M_MESSAGE(SENDER_ID, CHAT_ID, DATA)
VALUES(2,1,'здарова лошпедусы');

INSERT INTO M_MESSAGE(SENDER_ID, CHAT_ID, DATA)
VALUES(3,1,'и тебе привет');

INSERT INTO M_MESSAGE(SENDER_ID, CHAT_ID, DATA)
VALUES(1,1,'aboba...');




SELECT NAME,SENDER,MESSAGE
FROM M_USER 
CROSS JOIN LATERAL GET_CHATS_FOR_USER(M_USER.LOGIN) AS CHAT
CROSS JOIN LATERAL GET_MESSAGES_FOR_USER_IN_CHAT(M_USER.LOGIN, CHAT.ID)
WHERE M_USER.LOGIN = 'aboba';
